import type { Metadata } from "next";
import { Anta } from "next/font/google";
import "./globals.css";
import Provider from "@/providers";

const anta = Anta({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${anta.className}`}>{children}</body>
    </html>
  );
}
